travis:
  secure:
    BINSTAR_TOKEN: WhiaJZ56H+AFhWY25467BAYQVIVhQYW3/Y2ASX2vapGnaoGz6uEf1yGcNa3aZAHDRWuhf5uMVsOOtYnD2Q/7pEtyrVwcUm//DW/0ndJ2Fe0UmK2ofCSckRCx/wnrXmIRE9CKC3FVNPFb/D8qfjeWK7jY5l1k4IaMAfG0pvXHAxLDCvhCBArxCgBttZ+FcKg0FZaHvHFBVx24bleWjlIcETPgVteXkz5ZOZIgxzyWwPZ+7kGNwwoSVFN32om2y8FMhAhsj4YNdqUJA74jepUDSk4CVUL+CLnonHLpy37ExdfP37Bls7gE2DiuaBS5Hb0bLpKAHqw7yWBzBStem4uM/UZYo2/Gb2Gj88dLJkAPhYrJZUaZV4cBEXQB7obTR3l7yvuIUvrMSlzWJ3PloqUBFuTblzeHsivHG73edXrSENvYYIxZROW0+cnPHv06A3AiAcEhYgdn2cJk5L6QDnzAoj5MpzsJK8S+j0JP2tQp2nBofWC/DebAn5BDTbm6tRzUsfbjBcwLgzEtk1vumu1b93pzfXjrc67rRzvOP4yj/GYSYD3RRWEE0TqU1c5vcsbwN3TofmkX4itmNMfWu2lOdzNONXdmYoY38U+5LugsxTGpvk9Er83dBfbmbYt6etTGpOOgxwMfeejUIxr7xagwj+CHBlpwaT+VEpKpjZ8gs2o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
